baseURL = "https://liamtmk.github.io/portfolio/"
title = "Liam's Portfolio"
theme = "paige"
publishDir = "docs"

[languages.en]
languageCode = "en-us"
languagedirection = "ltr"
languageName = "English"
weight = 1

[languages.en.params.paige.site]
description = "My projects, an overview"