baseURL = 'https://liamtmk.github.io/portfolio/'
languageCode = 'en-us'
title = 'Liam's Portfolio'
theme = 'paige'
publishDir = 'docs'

[params]
  title = "Liam's Portfolio"
  subtitle = "Engineer â†’ AI/Software"