baseURL = "https://liamtmk.github.io/portfolio/"
title = "Liam's Portfolio"
theme = "paige"
publishDir = "docs"

[languages.en]
languageCode = "en-us"
languagedirection = "ltr"
languageName = "English"
weight = 1

[languages.en.params.paige.site]
description = "My projects, an overview"

[params.paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true
maximize_heading_levels = true
normalize_heading_levels = true

[params.paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true
disable_title = true

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true

[markup.goldmark.renderer]
unsafe = true